module.exports = {
  /**
   * FUNCTION func.
   * *"---------------------------------------------------------
   * " Local Interface:
   * " parameter_interface
   * "---------------------------------------------------------
   * ...
   * ENDFUNCTION.
   *
   * The parameter interface can either be a multi-line comment, if generated by
   * the function builder, or an explicit argument list.
   *
   * @see https://help.sap.com/doc/abapdocu_cp_index_htm/CLOUD/en-US/ABAPFUNCTION.html
   *
   */
  function_definition: $ =>
    seq(
      gen.kw("function"),
      field("name", $.identifier),
      repeat(
        choice(
          gen.kw_tagged("importing", $.parameters),
          gen.kw_tagged("exporting", $.parameters),
          gen.kw_tagged("changing", $.parameters),
          gen.kw_tagged("tables", $.parameters),
          gen.kw_tagged("raising", $.raising_list),
          gen.kw_tagged("exceptions", $.exceptions),
        ),
      ),
      ".",
      optional(alias($.statement_block, $.function_body)),
      gen.kw("endfunction"),
      ".",
    ),
};
