/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  aux_sym_inline_declaration_token1 = 1,
  aux_sym_inline_declaration_token2 = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_EQ = 5,
  anon_sym_DOT = 6,
  anon_sym_LPAREN2 = 7,
  anon_sym_RPAREN2 = 8,
  aux_sym_data_declaration_token1 = 9,
  aux_sym__type_reference_token1 = 10,
  aux_sym__like_reference_token1 = 11,
  aux_sym__data_value_token1 = 12,
  aux_sym__data_value_token2 = 13,
  aux_sym__data_value_token3 = 14,
  aux_sym__data_length_token1 = 15,
  aux_sym__data_decimals_token1 = 16,
  sym_type = 17,
  sym_identifier = 18,
  anon_sym_SQUOTE = 19,
  aux_sym_literal_string_token1 = 20,
  anon_sym_BQUOTE = 21,
  aux_sym_literal_string_token2 = 22,
  sym_literal_int = 23,
  sym_comment = 24,
  sym__whitespace = 25,
  sym__error_sentinel = 26,
  sym_source = 27,
  sym__statement = 28,
  sym__simple_statement = 29,
  sym_inline_declaration = 30,
  sym_inline_decl_assignment = 31,
  sym__expression = 32,
  sym_data_declaration = 33,
  sym__type_reference = 34,
  sym__like_reference = 35,
  sym__data_value = 36,
  sym__data_length = 37,
  sym__data_decimals = 38,
  sym_literal_string = 39,
  aux_sym_source_repeat1 = 40,
  aux_sym_data_declaration_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_inline_declaration_token1] = "data",
  [aux_sym_inline_declaration_token2] = "final",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN2] = "(",
  [anon_sym_RPAREN2] = ")",
  [aux_sym_data_declaration_token1] = "read-only",
  [aux_sym__type_reference_token1] = "type",
  [aux_sym__like_reference_token1] = "like",
  [aux_sym__data_value_token1] = "value",
  [aux_sym__data_value_token2] = "is",
  [aux_sym__data_value_token3] = "initial",
  [aux_sym__data_length_token1] = "length",
  [aux_sym__data_decimals_token1] = "decimals",
  [sym_type] = "type",
  [sym_identifier] = "identifier",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_literal_string_token1] = "literal_string_token1",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_literal_string_token2] = "literal_string_token2",
  [sym_literal_int] = "literal_int",
  [sym_comment] = "comment",
  [sym__whitespace] = "_whitespace",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_source] = "source",
  [sym__statement] = "_statement",
  [sym__simple_statement] = "_simple_statement",
  [sym_inline_declaration] = "inline_declaration",
  [sym_inline_decl_assignment] = "inline_decl_assignment",
  [sym__expression] = "_expression",
  [sym_data_declaration] = "data_declaration",
  [sym__type_reference] = "_type_reference",
  [sym__like_reference] = "_like_reference",
  [sym__data_value] = "_data_value",
  [sym__data_length] = "_data_length",
  [sym__data_decimals] = "_data_decimals",
  [sym_literal_string] = "literal_string",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_data_declaration_repeat1] = "data_declaration_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_inline_declaration_token1] = aux_sym_inline_declaration_token1,
  [aux_sym_inline_declaration_token2] = aux_sym_inline_declaration_token2,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [anon_sym_RPAREN2] = anon_sym_RPAREN,
  [aux_sym_data_declaration_token1] = aux_sym_data_declaration_token1,
  [aux_sym__type_reference_token1] = aux_sym__type_reference_token1,
  [aux_sym__like_reference_token1] = aux_sym__like_reference_token1,
  [aux_sym__data_value_token1] = aux_sym__data_value_token1,
  [aux_sym__data_value_token2] = aux_sym__data_value_token2,
  [aux_sym__data_value_token3] = aux_sym__data_value_token3,
  [aux_sym__data_length_token1] = aux_sym__data_length_token1,
  [aux_sym__data_decimals_token1] = aux_sym__data_decimals_token1,
  [sym_type] = sym_type,
  [sym_identifier] = sym_identifier,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_literal_string_token1] = aux_sym_literal_string_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_literal_string_token2] = aux_sym_literal_string_token2,
  [sym_literal_int] = sym_literal_int,
  [sym_comment] = sym_comment,
  [sym__whitespace] = sym__whitespace,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_source] = sym_source,
  [sym__statement] = sym__statement,
  [sym__simple_statement] = sym__simple_statement,
  [sym_inline_declaration] = sym_inline_declaration,
  [sym_inline_decl_assignment] = sym_inline_decl_assignment,
  [sym__expression] = sym__expression,
  [sym_data_declaration] = sym_data_declaration,
  [sym__type_reference] = sym__type_reference,
  [sym__like_reference] = sym__like_reference,
  [sym__data_value] = sym__data_value,
  [sym__data_length] = sym__data_length,
  [sym__data_decimals] = sym__data_decimals,
  [sym_literal_string] = sym_literal_string,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_data_declaration_repeat1] = aux_sym_data_declaration_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_inline_declaration_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_inline_declaration_token2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_data_declaration_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__type_reference_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__like_reference_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_value_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_value_token2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_value_token3] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_length_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_decimals_token1] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_literal_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_literal_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_literal_int] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_inline_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_decl_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_data_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__type_reference] = {
    .visible = false,
    .named = true,
  },
  [sym__like_reference] = {
    .visible = false,
    .named = true,
  },
  [sym__data_value] = {
    .visible = false,
    .named = true,
  },
  [sym__data_length] = {
    .visible = false,
    .named = true,
  },
  [sym__data_decimals] = {
    .visible = false,
    .named = true,
  },
  [sym_literal_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bufsize = 1,
  field_content = 2,
  field_decimals = 3,
  field_length = 4,
  field_like = 5,
  field_name = 6,
  field_readonly = 7,
  field_type = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bufsize] = "bufsize",
  [field_content] = "content",
  [field_decimals] = "decimals",
  [field_length] = "length",
  [field_like] = "like",
  [field_name] = "name",
  [field_readonly] = "readonly",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 1},
  [8] = {.index = 7, .length = 1},
  [9] = {.index = 8, .length = 7},
  [10] = {.index = 15, .length = 12},
  [11] = {.index = 27, .length = 4},
  [12] = {.index = 31, .length = 1},
  [13] = {.index = 32, .length = 2},
  [14] = {.index = 34, .length = 10},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_readonly, 0},
  [2] =
    {field_type, 0},
  [3] =
    {field_like, 0},
  [4] =
    {field_value, 0},
  [5] =
    {field_length, 0},
  [6] =
    {field_decimals, 0},
  [7] =
    {field_name, 2},
  [8] =
    {field_decimals, 2, .inherited = true},
    {field_length, 2, .inherited = true},
    {field_like, 2, .inherited = true},
    {field_name, 1},
    {field_readonly, 2, .inherited = true},
    {field_type, 2, .inherited = true},
    {field_value, 2, .inherited = true},
  [15] =
    {field_decimals, 0, .inherited = true},
    {field_decimals, 1, .inherited = true},
    {field_length, 0, .inherited = true},
    {field_length, 1, .inherited = true},
    {field_like, 0, .inherited = true},
    {field_like, 1, .inherited = true},
    {field_readonly, 0, .inherited = true},
    {field_readonly, 1, .inherited = true},
    {field_type, 0, .inherited = true},
    {field_type, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [27] =
    {field_bufsize, 2},
    {field_bufsize, 3},
    {field_bufsize, 4},
    {field_name, 1},
  [31] =
    {field_content, 1},
  [32] =
    {field_name, 2},
    {field_value, 5},
  [34] =
    {field_bufsize, 2},
    {field_bufsize, 3},
    {field_bufsize, 4},
    {field_decimals, 5, .inherited = true},
    {field_length, 5, .inherited = true},
    {field_like, 5, .inherited = true},
    {field_name, 1},
    {field_readonly, 5, .inherited = true},
    {field_type, 5, .inherited = true},
    {field_value, 5, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym__simple_statement,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym__simple_statement] = {.index = 0, .length = 3},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_data_declaration,
    sym_inline_decl_assignment,
    sym_inline_declaration,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(47);
      ADVANCE_MAP(
        '\'', 66,
        '(', 50,
        ')', 51,
        '-', 46,
        '.', 53,
        '=', 52,
        '`', 70,
        '"', 75,
        '*', 75,
        'D', 5,
        'd', 5,
        'F', 22,
        'f', 22,
        'I', 34,
        'i', 34,
        'L', 19,
        'l', 19,
        'R', 18,
        'r', 18,
        'T', 44,
        't', 44,
        'V', 6,
        'v', 6,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == ')') ADVANCE(51);
      if (lookahead == '"' ||
          lookahead == '*') ADVANCE(75);
      if (lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '(', 54,
        ')', 55,
        '.', 53,
        '"', 75,
        '*', 75,
        'D', 14,
        'd', 14,
        'L', 19,
        'l', 19,
        'R', 18,
        'r', 18,
        'T', 44,
        't', 44,
        'V', 6,
        'v', 6,
      );
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(37);
      END_STATE();
    case 4:
      if (lookahead == '"' ||
          lookahead == '*') ADVANCE(75);
      if (lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 5:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(41);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 9:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 12:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(3);
      END_STATE();
    case 14:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 16:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 17:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 18:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 19:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(33);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(62);
      END_STATE();
    case 22:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 23:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 25:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 26:
      if (lookahead == 'K' ||
          lookahead == 'k') ADVANCE(15);
      END_STATE();
    case 27:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 29:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 31:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(45);
      END_STATE();
    case 32:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(10);
      END_STATE();
    case 33:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 34:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(24);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(60);
      END_STATE();
    case 35:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 36:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 37:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 38:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 39:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(63);
      END_STATE();
    case 40:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(21);
      END_STATE();
    case 41:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(8);
      END_STATE();
    case 42:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(25);
      END_STATE();
    case 43:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 44:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(38);
      END_STATE();
    case 45:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(56);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_inline_declaration_token1);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_inline_declaration_token2);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RPAREN2);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_data_declaration_token1);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym__type_reference_token1);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym__like_reference_token1);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym__data_value_token1);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym__data_value_token2);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym__data_value_token3);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym__data_length_token1);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym__data_decimals_token1);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_literal_string_token1);
      if (lookahead == '\'') ADVANCE(75);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(69);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_literal_string_token1);
      if (lookahead == '"' ||
          lookahead == '*') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_literal_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_literal_string_token2);
      if (lookahead == '`') ADVANCE(75);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(73);
      if (lookahead != 0) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_literal_string_token2);
      if (lookahead == '"' ||
          lookahead == '*') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_literal_string_token2);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_literal_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(75);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 2, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 1, .external_lex_state = 2},
  [33] = {.lex_state = 1, .external_lex_state = 2},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 2, .external_lex_state = 2},
  [38] = {.lex_state = 1, .external_lex_state = 2},
  [39] = {.lex_state = 4, .external_lex_state = 2},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 2},
  [44] = {.lex_state = 68, .external_lex_state = 2},
  [45] = {.lex_state = 72, .external_lex_state = 2},
  [46] = {.lex_state = 1, .external_lex_state = 2},
  [47] = {.lex_state = 1, .external_lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_inline_declaration_token1] = ACTIONS(1),
    [aux_sym_inline_declaration_token2] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [anon_sym_RPAREN2] = ACTIONS(1),
    [aux_sym_data_declaration_token1] = ACTIONS(1),
    [aux_sym__type_reference_token1] = ACTIONS(1),
    [aux_sym__like_reference_token1] = ACTIONS(1),
    [aux_sym__data_value_token1] = ACTIONS(1),
    [aux_sym__data_value_token2] = ACTIONS(1),
    [aux_sym__data_value_token3] = ACTIONS(1),
    [aux_sym__data_length_token1] = ACTIONS(1),
    [aux_sym__data_decimals_token1] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_literal_int] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(3),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(35),
    [sym__statement] = STATE(7),
    [sym__simple_statement] = STATE(7),
    [sym_inline_declaration] = STATE(26),
    [sym_inline_decl_assignment] = STATE(26),
    [sym_data_declaration] = STATE(26),
    [aux_sym_source_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_inline_declaration_token1] = ACTIONS(7),
    [aux_sym_inline_declaration_token2] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      anon_sym_LPAREN2,
    ACTIONS(15), 1,
      aux_sym_data_declaration_token1,
    ACTIONS(17), 1,
      aux_sym__type_reference_token1,
    ACTIONS(19), 1,
      aux_sym__like_reference_token1,
    ACTIONS(21), 1,
      aux_sym__data_value_token1,
    ACTIONS(23), 1,
      aux_sym__data_length_token1,
    ACTIONS(25), 1,
      aux_sym__data_decimals_token1,
    STATE(3), 1,
      aux_sym_data_declaration_repeat1,
    STATE(9), 1,
      sym__data_decimals,
    STATE(10), 1,
      sym__like_reference,
    STATE(11), 1,
      sym__data_length,
    STATE(13), 1,
      sym__type_reference,
    STATE(14), 1,
      sym__data_value,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [47] = 14,
    ACTIONS(15), 1,
      aux_sym_data_declaration_token1,
    ACTIONS(17), 1,
      aux_sym__type_reference_token1,
    ACTIONS(19), 1,
      aux_sym__like_reference_token1,
    ACTIONS(21), 1,
      aux_sym__data_value_token1,
    ACTIONS(23), 1,
      aux_sym__data_length_token1,
    ACTIONS(25), 1,
      aux_sym__data_decimals_token1,
    ACTIONS(27), 1,
      anon_sym_DOT,
    STATE(5), 1,
      aux_sym_data_declaration_repeat1,
    STATE(9), 1,
      sym__data_decimals,
    STATE(10), 1,
      sym__like_reference,
    STATE(11), 1,
      sym__data_length,
    STATE(13), 1,
      sym__type_reference,
    STATE(14), 1,
      sym__data_value,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [91] = 14,
    ACTIONS(15), 1,
      aux_sym_data_declaration_token1,
    ACTIONS(17), 1,
      aux_sym__type_reference_token1,
    ACTIONS(19), 1,
      aux_sym__like_reference_token1,
    ACTIONS(21), 1,
      aux_sym__data_value_token1,
    ACTIONS(23), 1,
      aux_sym__data_length_token1,
    ACTIONS(25), 1,
      aux_sym__data_decimals_token1,
    ACTIONS(29), 1,
      anon_sym_DOT,
    STATE(5), 1,
      aux_sym_data_declaration_repeat1,
    STATE(9), 1,
      sym__data_decimals,
    STATE(10), 1,
      sym__like_reference,
    STATE(11), 1,
      sym__data_length,
    STATE(13), 1,
      sym__type_reference,
    STATE(14), 1,
      sym__data_value,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [135] = 14,
    ACTIONS(31), 1,
      anon_sym_DOT,
    ACTIONS(33), 1,
      aux_sym_data_declaration_token1,
    ACTIONS(36), 1,
      aux_sym__type_reference_token1,
    ACTIONS(39), 1,
      aux_sym__like_reference_token1,
    ACTIONS(42), 1,
      aux_sym__data_value_token1,
    ACTIONS(45), 1,
      aux_sym__data_length_token1,
    ACTIONS(48), 1,
      aux_sym__data_decimals_token1,
    STATE(5), 1,
      aux_sym_data_declaration_repeat1,
    STATE(9), 1,
      sym__data_decimals,
    STATE(10), 1,
      sym__like_reference,
    STATE(11), 1,
      sym__data_length,
    STATE(13), 1,
      sym__type_reference,
    STATE(14), 1,
      sym__data_value,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [179] = 14,
    ACTIONS(15), 1,
      aux_sym_data_declaration_token1,
    ACTIONS(17), 1,
      aux_sym__type_reference_token1,
    ACTIONS(19), 1,
      aux_sym__like_reference_token1,
    ACTIONS(21), 1,
      aux_sym__data_value_token1,
    ACTIONS(23), 1,
      aux_sym__data_length_token1,
    ACTIONS(25), 1,
      aux_sym__data_decimals_token1,
    ACTIONS(51), 1,
      anon_sym_DOT,
    STATE(4), 1,
      aux_sym_data_declaration_repeat1,
    STATE(9), 1,
      sym__data_decimals,
    STATE(10), 1,
      sym__like_reference,
    STATE(11), 1,
      sym__data_length,
    STATE(13), 1,
      sym__type_reference,
    STATE(14), 1,
      sym__data_value,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [223] = 6,
    ACTIONS(7), 1,
      aux_sym_inline_declaration_token1,
    ACTIONS(9), 1,
      aux_sym_inline_declaration_token2,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    STATE(8), 3,
      sym__statement,
      sym__simple_statement,
      aux_sym_source_repeat1,
    STATE(26), 3,
      sym_inline_declaration,
      sym_inline_decl_assignment,
      sym_data_declaration,
  [247] = 6,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      aux_sym_inline_declaration_token1,
    ACTIONS(60), 1,
      aux_sym_inline_declaration_token2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    STATE(8), 3,
      sym__statement,
      sym__simple_statement,
      aux_sym_source_repeat1,
    STATE(26), 3,
      sym_inline_declaration,
      sym_inline_decl_assignment,
      sym_data_declaration,
  [271] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(63), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [285] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(65), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [299] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(67), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [313] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(69), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [327] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(71), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [341] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(73), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [355] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(75), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [369] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(77), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [383] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(79), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [397] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(81), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [411] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(83), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [425] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(85), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [439] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(87), 7,
      anon_sym_DOT,
      aux_sym_data_declaration_token1,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [453] = 5,
    ACTIONS(89), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_BQUOTE,
    ACTIONS(93), 1,
      sym_literal_int,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    STATE(42), 2,
      sym__expression,
      sym_literal_string,
  [471] = 5,
    ACTIONS(89), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_BQUOTE,
    ACTIONS(95), 1,
      sym_literal_int,
    STATE(15), 1,
      sym_literal_string,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [488] = 5,
    ACTIONS(89), 1,
      anon_sym_SQUOTE,
    ACTIONS(91), 1,
      anon_sym_BQUOTE,
    ACTIONS(97), 1,
      aux_sym__data_value_token2,
    STATE(16), 1,
      sym_literal_string,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [505] = 3,
    ACTIONS(101), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
  [518] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
  [528] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
  [538] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(107), 3,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
  [548] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
  [558] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(111), 3,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
  [568] = 2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
    ACTIONS(113), 3,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
  [578] = 3,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [589] = 2,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [597] = 2,
    ACTIONS(119), 1,
      sym_literal_int,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [605] = 2,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [613] = 2,
    ACTIONS(123), 1,
      sym_literal_int,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [621] = 2,
    ACTIONS(125), 1,
      anon_sym_RPAREN2,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [629] = 2,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [637] = 2,
    ACTIONS(129), 1,
      sym_type,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [645] = 2,
    ACTIONS(131), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [653] = 2,
    ACTIONS(131), 1,
      anon_sym_BQUOTE,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [661] = 2,
    ACTIONS(133), 1,
      anon_sym_DOT,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [669] = 2,
    ACTIONS(135), 1,
      aux_sym__data_value_token3,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [677] = 3,
    ACTIONS(3), 1,
      sym__whitespace,
    ACTIONS(137), 1,
      aux_sym_literal_string_token1,
    ACTIONS(139), 1,
      sym_comment,
  [687] = 3,
    ACTIONS(3), 1,
      sym__whitespace,
    ACTIONS(139), 1,
      sym_comment,
    ACTIONS(141), 1,
      aux_sym_literal_string_token2,
  [697] = 2,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
  [705] = 2,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym__whitespace,
      sym_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 91,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 179,
  [SMALL_STATE(7)] = 223,
  [SMALL_STATE(8)] = 247,
  [SMALL_STATE(9)] = 271,
  [SMALL_STATE(10)] = 285,
  [SMALL_STATE(11)] = 299,
  [SMALL_STATE(12)] = 313,
  [SMALL_STATE(13)] = 327,
  [SMALL_STATE(14)] = 341,
  [SMALL_STATE(15)] = 355,
  [SMALL_STATE(16)] = 369,
  [SMALL_STATE(17)] = 383,
  [SMALL_STATE(18)] = 397,
  [SMALL_STATE(19)] = 411,
  [SMALL_STATE(20)] = 425,
  [SMALL_STATE(21)] = 439,
  [SMALL_STATE(22)] = 453,
  [SMALL_STATE(23)] = 471,
  [SMALL_STATE(24)] = 488,
  [SMALL_STATE(25)] = 505,
  [SMALL_STATE(26)] = 518,
  [SMALL_STATE(27)] = 528,
  [SMALL_STATE(28)] = 538,
  [SMALL_STATE(29)] = 548,
  [SMALL_STATE(30)] = 558,
  [SMALL_STATE(31)] = 568,
  [SMALL_STATE(32)] = 578,
  [SMALL_STATE(33)] = 589,
  [SMALL_STATE(34)] = 597,
  [SMALL_STATE(35)] = 605,
  [SMALL_STATE(36)] = 613,
  [SMALL_STATE(37)] = 621,
  [SMALL_STATE(38)] = 629,
  [SMALL_STATE(39)] = 637,
  [SMALL_STATE(40)] = 645,
  [SMALL_STATE(41)] = 653,
  [SMALL_STATE(42)] = 661,
  [SMALL_STATE(43)] = 669,
  [SMALL_STATE(44)] = 677,
  [SMALL_STATE(45)] = 687,
  [SMALL_STATE(46)] = 697,
  [SMALL_STATE(47)] = 705,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 2, 0, 10),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 2, 0, 10), SHIFT_REPEAT(12),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 2, 0, 10), SHIFT_REPEAT(39),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 2, 0, 10), SHIFT_REPEAT(46),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 2, 0, 10), SHIFT_REPEAT(24),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 2, 0, 10), SHIFT_REPEAT(23),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 2, 0, 10), SHIFT_REPEAT(36),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 1, 0, 7),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 1, 0, 4),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 1, 0, 6),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 1, 0, 2),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 1, 0, 3),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 1, 0, 5),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_length, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_value, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_reference, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__like_reference, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_decimals, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_value, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_string, 3, 0, 12),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_declaration, 4, 0, 8),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_statement, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_declaration, 3, 0, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_declaration, 6, 0, 11),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_declaration, 4, 0, 9),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_decl_assignment, 7, 0, 13),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_declaration, 7, 0, 14),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [121] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__whitespace = 0,
  ts_external_token__error_sentinel = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__whitespace] = sym__whitespace,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__whitespace] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__whitespace] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_abap_external_scanner_create(void);
void tree_sitter_abap_external_scanner_destroy(void *);
bool tree_sitter_abap_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_abap_external_scanner_serialize(void *, char *);
void tree_sitter_abap_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_abap(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_abap_external_scanner_create,
      tree_sitter_abap_external_scanner_destroy,
      tree_sitter_abap_external_scanner_scan,
      tree_sitter_abap_external_scanner_serialize,
      tree_sitter_abap_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "abap",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
