/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 65
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_inline_declaration_token1 = 2,
  aux_sym_inline_declaration_token2 = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_EQ = 6,
  anon_sym_DOT = 7,
  aux_sym__scalar_declaration_body_token1 = 8,
  aux_sym__scalar_declaration_body_token2 = 9,
  anon_sym_COLON = 10,
  anon_sym_COMMA = 11,
  aux_sym_report_statement_token1 = 12,
  aux_sym__type_reference_token1 = 13,
  aux_sym__like_reference_token1 = 14,
  aux_sym__data_value_token1 = 15,
  aux_sym__data_value_token2 = 16,
  aux_sym__data_value_token3 = 17,
  aux_sym__data_length_token1 = 18,
  aux_sym__data_decimals_token1 = 19,
  sym_type = 20,
  sym_number = 21,
  aux_sym__immediate_identifier_token1 = 22,
  anon_sym_SQUOTE = 23,
  aux_sym_literal_string_token1 = 24,
  anon_sym_BQUOTE = 25,
  aux_sym_literal_string_token2 = 26,
  aux_sym_comment_token1 = 27,
  sym__inline_comment = 28,
  sym__begin_line_comment = 29,
  sym__whitespace = 30,
  sym__error_sentinel = 31,
  sym_source = 32,
  sym__statement = 33,
  sym__simple_statement = 34,
  sym_inline_declaration = 35,
  sym__expression = 36,
  sym__scalar_declaration_body = 37,
  sym_data_declaration = 38,
  sym_single_data_declaration = 39,
  sym_multi_data_declaration = 40,
  sym_report_statement = 41,
  sym__type_reference = 42,
  sym__like_reference = 43,
  sym__data_value = 44,
  sym__data_length = 45,
  sym__data_decimals = 46,
  sym__immediate_identifier = 47,
  sym_literal_string = 48,
  sym_comment = 49,
  aux_sym_source_repeat1 = 50,
  aux_sym__scalar_declaration_body_repeat1 = 51,
  aux_sym_multi_data_declaration_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_inline_declaration_token1] = "data",
  [aux_sym_inline_declaration_token2] = "final",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [aux_sym__scalar_declaration_body_token1] = "number",
  [aux_sym__scalar_declaration_body_token2] = "read-only",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [aux_sym_report_statement_token1] = "report",
  [aux_sym__type_reference_token1] = "type",
  [aux_sym__like_reference_token1] = "like",
  [aux_sym__data_value_token1] = "value",
  [aux_sym__data_value_token2] = "is",
  [aux_sym__data_value_token3] = "initial",
  [aux_sym__data_length_token1] = "length",
  [aux_sym__data_decimals_token1] = "decimals",
  [sym_type] = "type",
  [sym_number] = "number",
  [aux_sym__immediate_identifier_token1] = "identifier",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_literal_string_token1] = "literal_string_token1",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_literal_string_token2] = "literal_string_token2",
  [aux_sym_comment_token1] = "comment_token1",
  [sym__inline_comment] = "_inline_comment",
  [sym__begin_line_comment] = "_begin_line_comment",
  [sym__whitespace] = "_whitespace",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_source] = "source",
  [sym__statement] = "_statement",
  [sym__simple_statement] = "_simple_statement",
  [sym_inline_declaration] = "inline_declaration",
  [sym__expression] = "_expression",
  [sym__scalar_declaration_body] = "_scalar_declaration_body",
  [sym_data_declaration] = "data_declaration",
  [sym_single_data_declaration] = "single_data_declaration",
  [sym_multi_data_declaration] = "multi_data_declaration",
  [sym_report_statement] = "report_statement",
  [sym__type_reference] = "_type_reference",
  [sym__like_reference] = "_like_reference",
  [sym__data_value] = "_data_value",
  [sym__data_length] = "_data_length",
  [sym__data_decimals] = "_data_decimals",
  [sym__immediate_identifier] = "_immediate_identifier",
  [sym_literal_string] = "literal_string",
  [sym_comment] = "comment",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym__scalar_declaration_body_repeat1] = "_scalar_declaration_body_repeat1",
  [aux_sym_multi_data_declaration_repeat1] = "multi_data_declaration_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_inline_declaration_token1] = aux_sym_inline_declaration_token1,
  [aux_sym_inline_declaration_token2] = aux_sym_inline_declaration_token2,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym__scalar_declaration_body_token1] = sym_number,
  [aux_sym__scalar_declaration_body_token2] = aux_sym__scalar_declaration_body_token2,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_report_statement_token1] = aux_sym_report_statement_token1,
  [aux_sym__type_reference_token1] = aux_sym__type_reference_token1,
  [aux_sym__like_reference_token1] = aux_sym__like_reference_token1,
  [aux_sym__data_value_token1] = aux_sym__data_value_token1,
  [aux_sym__data_value_token2] = aux_sym__data_value_token2,
  [aux_sym__data_value_token3] = aux_sym__data_value_token3,
  [aux_sym__data_length_token1] = aux_sym__data_length_token1,
  [aux_sym__data_decimals_token1] = aux_sym__data_decimals_token1,
  [sym_type] = sym_type,
  [sym_number] = sym_number,
  [aux_sym__immediate_identifier_token1] = sym_identifier,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_literal_string_token1] = aux_sym_literal_string_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_literal_string_token2] = aux_sym_literal_string_token2,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym__inline_comment] = sym__inline_comment,
  [sym__begin_line_comment] = sym__begin_line_comment,
  [sym__whitespace] = sym__whitespace,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_source] = sym_source,
  [sym__statement] = sym__statement,
  [sym__simple_statement] = sym__simple_statement,
  [sym_inline_declaration] = sym_inline_declaration,
  [sym__expression] = sym__expression,
  [sym__scalar_declaration_body] = sym__scalar_declaration_body,
  [sym_data_declaration] = sym_data_declaration,
  [sym_single_data_declaration] = sym_single_data_declaration,
  [sym_multi_data_declaration] = sym_multi_data_declaration,
  [sym_report_statement] = sym_report_statement,
  [sym__type_reference] = sym__type_reference,
  [sym__like_reference] = sym__like_reference,
  [sym__data_value] = sym__data_value,
  [sym__data_length] = sym__data_length,
  [sym__data_decimals] = sym__data_decimals,
  [sym__immediate_identifier] = sym__immediate_identifier,
  [sym_literal_string] = sym_literal_string,
  [sym_comment] = sym_comment,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym__scalar_declaration_body_repeat1] = aux_sym__scalar_declaration_body_repeat1,
  [aux_sym_multi_data_declaration_repeat1] = aux_sym_multi_data_declaration_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_inline_declaration_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_inline_declaration_token2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__scalar_declaration_body_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__scalar_declaration_body_token2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_report_statement_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__type_reference_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__like_reference_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_value_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_value_token2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_value_token3] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_length_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_decimals_token1] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__immediate_identifier_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_literal_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_literal_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__inline_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__begin_line_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_inline_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__scalar_declaration_body] = {
    .visible = false,
    .named = true,
  },
  [sym_data_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_single_data_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_multi_data_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_report_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__type_reference] = {
    .visible = false,
    .named = true,
  },
  [sym__like_reference] = {
    .visible = false,
    .named = true,
  },
  [sym__data_value] = {
    .visible = false,
    .named = true,
  },
  [sym__data_length] = {
    .visible = false,
    .named = true,
  },
  [sym__data_decimals] = {
    .visible = false,
    .named = true,
  },
  [sym__immediate_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_literal_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__scalar_declaration_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multi_data_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bufsize = 1,
  field_content = 2,
  field_decimals = 3,
  field_length = 4,
  field_like = 5,
  field_name = 6,
  field_readonly = 7,
  field_type = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bufsize] = "bufsize",
  [field_content] = "content",
  [field_decimals] = "decimals",
  [field_length] = "length",
  [field_like] = "like",
  [field_name] = "name",
  [field_readonly] = "readonly",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 8},
  [4] = {.index = 10, .length = 1},
  [5] = {.index = 11, .length = 1},
  [6] = {.index = 12, .length = 1},
  [7] = {.index = 13, .length = 1},
  [8] = {.index = 14, .length = 1},
  [9] = {.index = 15, .length = 6},
  [10] = {.index = 21, .length = 1},
  [11] = {.index = 22, .length = 12},
  [12] = {.index = 34, .length = 9},
  [13] = {.index = 43, .length = 1},
  [14] = {.index = 44, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_readonly, 0},
  [2] =
    {field_bufsize, 1, .inherited = true},
    {field_decimals, 1, .inherited = true},
    {field_length, 1, .inherited = true},
    {field_like, 1, .inherited = true},
    {field_name, 0},
    {field_readonly, 1, .inherited = true},
    {field_type, 1, .inherited = true},
    {field_value, 1, .inherited = true},
  [10] =
    {field_type, 0},
  [11] =
    {field_like, 0},
  [12] =
    {field_value, 0},
  [13] =
    {field_length, 0},
  [14] =
    {field_decimals, 0},
  [15] =
    {field_decimals, 0, .inherited = true},
    {field_length, 0, .inherited = true},
    {field_like, 0, .inherited = true},
    {field_readonly, 0, .inherited = true},
    {field_type, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [21] =
    {field_name, 2},
  [22] =
    {field_decimals, 0, .inherited = true},
    {field_decimals, 1, .inherited = true},
    {field_length, 0, .inherited = true},
    {field_length, 1, .inherited = true},
    {field_like, 0, .inherited = true},
    {field_like, 1, .inherited = true},
    {field_readonly, 0, .inherited = true},
    {field_readonly, 1, .inherited = true},
    {field_type, 0, .inherited = true},
    {field_type, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [34] =
    {field_bufsize, 0},
    {field_bufsize, 1},
    {field_bufsize, 2},
    {field_decimals, 3, .inherited = true},
    {field_length, 3, .inherited = true},
    {field_like, 3, .inherited = true},
    {field_readonly, 3, .inherited = true},
    {field_type, 3, .inherited = true},
    {field_value, 3, .inherited = true},
  [43] =
    {field_content, 1},
  [44] =
    {field_name, 2},
    {field_value, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym__simple_statement,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym__simple_statement] = {.index = 0, .length = 4},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_inline_declaration,
    sym_multi_data_declaration,
    sym_report_statement,
    sym_single_data_declaration,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 28,
        '\'', 18,
        '(', 7,
        ')', 8,
        ',', 13,
        '-', 3,
        '.', 10,
        ':', 12,
        '=', 9,
        '`', 22,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '-') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 28,
        '\'', 18,
        '(', 7,
        ',', 13,
        '-', 4,
        '.', 10,
        ':', 12,
        '=', 9,
        '`', 22,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__scalar_declaration_body_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__immediate_identifier_token1);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_literal_string_token1);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_literal_string_token1);
      if (lookahead == '\'') ADVANCE(28);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(21);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_literal_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_literal_string_token2);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_literal_string_token2);
      if (lookahead == '`') ADVANCE(28);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(25);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_literal_string_token2);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '"') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__inline_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(28);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'D', 1,
        'd', 1,
        'F', 2,
        'f', 2,
        'I', 3,
        'i', 3,
        'L', 4,
        'l', 4,
        'R', 5,
        'r', 5,
        'T', 6,
        't', 6,
        'V', 7,
        'v', 7,
      );
      END_STATE();
    case 1:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(8);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(11);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym__data_value_token2);
      END_STATE();
    case 13:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'K' ||
          lookahead == 'k') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(24);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_inline_declaration_token1);
      END_STATE();
    case 29:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__like_reference_token1);
      END_STATE();
    case 34:
      if (lookahead == '-') ADVANCE(42);
      END_STATE();
    case 35:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym__type_reference_token1);
      END_STATE();
    case 37:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 38:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_inline_declaration_token2);
      END_STATE();
    case 40:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 41:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(47);
      END_STATE();
    case 42:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 43:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(49);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__data_value_token1);
      END_STATE();
    case 45:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 46:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__data_length_token1);
      END_STATE();
    case 48:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_report_statement_token1);
      END_STATE();
    case 50:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym__data_value_token3);
      END_STATE();
    case 52:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym__data_decimals_token1);
      END_STATE();
    case 54:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym__scalar_declaration_body_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 5, .external_lex_state = 2},
  [2] = {.lex_state = 5, .external_lex_state = 2},
  [3] = {.lex_state = 5, .external_lex_state = 2},
  [4] = {.lex_state = 5, .external_lex_state = 2},
  [5] = {.lex_state = 5, .external_lex_state = 2},
  [6] = {.lex_state = 5, .external_lex_state = 2},
  [7] = {.lex_state = 5, .external_lex_state = 2},
  [8] = {.lex_state = 5, .external_lex_state = 2},
  [9] = {.lex_state = 5, .external_lex_state = 2},
  [10] = {.lex_state = 5, .external_lex_state = 2},
  [11] = {.lex_state = 5, .external_lex_state = 2},
  [12] = {.lex_state = 5, .external_lex_state = 2},
  [13] = {.lex_state = 5, .external_lex_state = 2},
  [14] = {.lex_state = 5, .external_lex_state = 2},
  [15] = {.lex_state = 5, .external_lex_state = 2},
  [16] = {.lex_state = 5, .external_lex_state = 2},
  [17] = {.lex_state = 5, .external_lex_state = 2},
  [18] = {.lex_state = 5, .external_lex_state = 2},
  [19] = {.lex_state = 5, .external_lex_state = 2},
  [20] = {.lex_state = 5, .external_lex_state = 2},
  [21] = {.lex_state = 5, .external_lex_state = 2},
  [22] = {.lex_state = 5, .external_lex_state = 2},
  [23] = {.lex_state = 5, .external_lex_state = 2},
  [24] = {.lex_state = 5, .external_lex_state = 2},
  [25] = {.lex_state = 5, .external_lex_state = 2},
  [26] = {.lex_state = 5, .external_lex_state = 2},
  [27] = {.lex_state = 5, .external_lex_state = 2},
  [28] = {.lex_state = 5, .external_lex_state = 2},
  [29] = {.lex_state = 5, .external_lex_state = 2},
  [30] = {.lex_state = 5, .external_lex_state = 2},
  [31] = {.lex_state = 5, .external_lex_state = 2},
  [32] = {.lex_state = 5, .external_lex_state = 2},
  [33] = {.lex_state = 5, .external_lex_state = 2},
  [34] = {.lex_state = 5, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 0, .external_lex_state = 2},
  [38] = {.lex_state = 1, .external_lex_state = 2},
  [39] = {.lex_state = 5, .external_lex_state = 2},
  [40] = {.lex_state = 5, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 5, .external_lex_state = 2},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 19, .external_lex_state = 2},
  [48] = {.lex_state = 23, .external_lex_state = 2},
  [49] = {.lex_state = 26, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 0, .external_lex_state = 2},
  [53] = {.lex_state = 5, .external_lex_state = 2},
  [54] = {.lex_state = 5, .external_lex_state = 2},
  [55] = {.lex_state = 1, .external_lex_state = 2},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 0, .external_lex_state = 2},
  [59] = {.lex_state = 0, .external_lex_state = 2},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 2, .external_lex_state = 2},
  [62] = {.lex_state = 5, .external_lex_state = 2},
  [63] = {(TSStateId)(-1),},
  [64] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_inline_declaration_token1] = ACTIONS(1),
    [aux_sym_inline_declaration_token2] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym__scalar_declaration_body_token1] = ACTIONS(1),
    [aux_sym__scalar_declaration_body_token2] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_report_statement_token1] = ACTIONS(1),
    [aux_sym__type_reference_token1] = ACTIONS(1),
    [aux_sym__like_reference_token1] = ACTIONS(1),
    [aux_sym__data_value_token1] = ACTIONS(1),
    [aux_sym__data_value_token2] = ACTIONS(1),
    [aux_sym__data_value_token3] = ACTIONS(1),
    [aux_sym__data_length_token1] = ACTIONS(1),
    [aux_sym__data_decimals_token1] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym__immediate_identifier_token1] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym__inline_comment] = ACTIONS(3),
    [sym__begin_line_comment] = ACTIONS(5),
    [sym__whitespace] = ACTIONS(7),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(52),
    [sym__statement] = STATE(28),
    [sym__simple_statement] = STATE(29),
    [sym_inline_declaration] = STATE(30),
    [sym_single_data_declaration] = STATE(30),
    [sym_multi_data_declaration] = STATE(30),
    [sym_report_statement] = STATE(30),
    [sym_comment] = STATE(1),
    [aux_sym_source_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(9),
    [aux_sym_inline_declaration_token1] = ACTIONS(11),
    [aux_sym_inline_declaration_token2] = ACTIONS(13),
    [aux_sym_report_statement_token1] = ACTIONS(15),
    [sym__inline_comment] = ACTIONS(3),
    [sym__begin_line_comment] = ACTIONS(5),
    [sym__whitespace] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      aux_sym__scalar_declaration_body_token2,
    ACTIONS(23), 1,
      aux_sym__type_reference_token1,
    ACTIONS(25), 1,
      aux_sym__like_reference_token1,
    ACTIONS(27), 1,
      aux_sym__data_value_token1,
    ACTIONS(29), 1,
      aux_sym__data_length_token1,
    ACTIONS(31), 1,
      aux_sym__data_decimals_token1,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      aux_sym__scalar_declaration_body_repeat1,
    STATE(10), 1,
      sym__type_reference,
    STATE(11), 1,
      sym__data_value,
    STATE(12), 1,
      sym__like_reference,
    STATE(13), 1,
      sym__data_length,
    STATE(14), 1,
      sym__data_decimals,
    STATE(41), 1,
      sym__scalar_declaration_body,
    ACTIONS(19), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [59] = 17,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(21), 1,
      aux_sym__scalar_declaration_body_token2,
    ACTIONS(23), 1,
      aux_sym__type_reference_token1,
    ACTIONS(25), 1,
      aux_sym__like_reference_token1,
    ACTIONS(27), 1,
      aux_sym__data_value_token1,
    ACTIONS(29), 1,
      aux_sym__data_length_token1,
    ACTIONS(31), 1,
      aux_sym__data_decimals_token1,
    STATE(3), 1,
      sym_comment,
    STATE(5), 1,
      aux_sym__scalar_declaration_body_repeat1,
    STATE(10), 1,
      sym__type_reference,
    STATE(11), 1,
      sym__data_value,
    STATE(12), 1,
      sym__like_reference,
    STATE(13), 1,
      sym__data_length,
    STATE(14), 1,
      sym__data_decimals,
    ACTIONS(33), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [112] = 17,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(21), 1,
      aux_sym__scalar_declaration_body_token2,
    ACTIONS(23), 1,
      aux_sym__type_reference_token1,
    ACTIONS(25), 1,
      aux_sym__like_reference_token1,
    ACTIONS(27), 1,
      aux_sym__data_value_token1,
    ACTIONS(29), 1,
      aux_sym__data_length_token1,
    ACTIONS(31), 1,
      aux_sym__data_decimals_token1,
    STATE(4), 1,
      sym_comment,
    STATE(5), 1,
      aux_sym__scalar_declaration_body_repeat1,
    STATE(10), 1,
      sym__type_reference,
    STATE(11), 1,
      sym__data_value,
    STATE(12), 1,
      sym__like_reference,
    STATE(13), 1,
      sym__data_length,
    STATE(14), 1,
      sym__data_decimals,
    ACTIONS(35), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [165] = 16,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(39), 1,
      aux_sym__scalar_declaration_body_token2,
    ACTIONS(42), 1,
      aux_sym__type_reference_token1,
    ACTIONS(45), 1,
      aux_sym__like_reference_token1,
    ACTIONS(48), 1,
      aux_sym__data_value_token1,
    ACTIONS(51), 1,
      aux_sym__data_length_token1,
    ACTIONS(54), 1,
      aux_sym__data_decimals_token1,
    STATE(10), 1,
      sym__type_reference,
    STATE(11), 1,
      sym__data_value,
    STATE(12), 1,
      sym__like_reference,
    STATE(13), 1,
      sym__data_length,
    STATE(14), 1,
      sym__data_decimals,
    ACTIONS(37), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
    STATE(5), 2,
      sym_comment,
      aux_sym__scalar_declaration_body_repeat1,
  [216] = 16,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(21), 1,
      aux_sym__scalar_declaration_body_token2,
    ACTIONS(23), 1,
      aux_sym__type_reference_token1,
    ACTIONS(25), 1,
      aux_sym__like_reference_token1,
    ACTIONS(27), 1,
      aux_sym__data_value_token1,
    ACTIONS(29), 1,
      aux_sym__data_length_token1,
    ACTIONS(31), 1,
      aux_sym__data_decimals_token1,
    STATE(4), 1,
      aux_sym__scalar_declaration_body_repeat1,
    STATE(6), 1,
      sym_comment,
    STATE(10), 1,
      sym__type_reference,
    STATE(11), 1,
      sym__data_value,
    STATE(12), 1,
      sym__like_reference,
    STATE(13), 1,
      sym__data_length,
    STATE(14), 1,
      sym__data_decimals,
  [265] = 12,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(11), 1,
      aux_sym_inline_declaration_token1,
    ACTIONS(13), 1,
      aux_sym_inline_declaration_token2,
    ACTIONS(15), 1,
      aux_sym_report_statement_token1,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_source_repeat1,
    STATE(28), 1,
      sym__statement,
    STATE(29), 1,
      sym__simple_statement,
    STATE(30), 4,
      sym_inline_declaration,
      sym_single_data_declaration,
      sym_multi_data_declaration,
      sym_report_statement,
  [305] = 11,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      aux_sym_inline_declaration_token1,
    ACTIONS(64), 1,
      aux_sym_inline_declaration_token2,
    ACTIONS(67), 1,
      aux_sym_report_statement_token1,
    STATE(28), 1,
      sym__statement,
    STATE(29), 1,
      sym__simple_statement,
    STATE(8), 2,
      sym_comment,
      aux_sym_source_repeat1,
    STATE(30), 4,
      sym_inline_declaration,
      sym_single_data_declaration,
      sym_multi_data_declaration,
      sym_report_statement,
  [343] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(9), 1,
      sym_comment,
    ACTIONS(70), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [366] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(10), 1,
      sym_comment,
    ACTIONS(72), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [389] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(11), 1,
      sym_comment,
    ACTIONS(74), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [412] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(12), 1,
      sym_comment,
    ACTIONS(76), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [435] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(13), 1,
      sym_comment,
    ACTIONS(78), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [458] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(14), 1,
      sym_comment,
    ACTIONS(80), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [481] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(15), 1,
      sym_comment,
    ACTIONS(82), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [504] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(16), 1,
      sym_comment,
    ACTIONS(84), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [527] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(17), 1,
      sym_comment,
    ACTIONS(86), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [550] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(18), 1,
      sym_comment,
    ACTIONS(88), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [573] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(19), 1,
      sym_comment,
    ACTIONS(90), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [596] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(20), 1,
      sym_comment,
    ACTIONS(92), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [619] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(21), 1,
      sym_comment,
    ACTIONS(94), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [642] = 9,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(96), 1,
      aux_sym__data_value_token2,
    ACTIONS(98), 1,
      sym_number,
    ACTIONS(100), 1,
      anon_sym_SQUOTE,
    ACTIONS(102), 1,
      anon_sym_BQUOTE,
    STATE(15), 1,
      sym_literal_string,
    STATE(22), 1,
      sym_comment,
  [670] = 9,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(100), 1,
      anon_sym_SQUOTE,
    ACTIONS(102), 1,
      anon_sym_BQUOTE,
    ACTIONS(104), 1,
      sym_number,
    STATE(23), 1,
      sym_comment,
    STATE(59), 1,
      sym_literal_string,
    STATE(60), 1,
      sym__expression,
  [698] = 6,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(108), 1,
      anon_sym_EQ,
    STATE(24), 1,
      sym_comment,
    ACTIONS(106), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [720] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(25), 1,
      sym_comment,
    ACTIONS(110), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [739] = 8,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(100), 1,
      anon_sym_SQUOTE,
    ACTIONS(102), 1,
      anon_sym_BQUOTE,
    ACTIONS(112), 1,
      sym_number,
    STATE(21), 1,
      sym_literal_string,
    STATE(26), 1,
      sym_comment,
  [764] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(27), 1,
      sym_comment,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [783] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(28), 1,
      sym_comment,
    ACTIONS(116), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [802] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(29), 1,
      sym_comment,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [821] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(30), 1,
      sym_comment,
    ACTIONS(120), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [840] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(31), 1,
      sym_comment,
    ACTIONS(122), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [859] = 8,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(124), 1,
      sym_identifier,
    ACTIONS(126), 1,
      anon_sym_LPAREN,
    ACTIONS(128), 1,
      anon_sym_COLON,
    STATE(32), 1,
      sym_comment,
    STATE(44), 1,
      sym_data_declaration,
  [884] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(33), 1,
      sym_comment,
    ACTIONS(130), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [903] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(34), 1,
      sym_comment,
    ACTIONS(132), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [922] = 7,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(134), 1,
      anon_sym_DOT,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      sym_comment,
    STATE(37), 1,
      aux_sym_multi_data_declaration_repeat1,
  [944] = 7,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_DOT,
    STATE(35), 1,
      aux_sym_multi_data_declaration_repeat1,
    STATE(36), 1,
      sym_comment,
  [966] = 6,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(140), 1,
      anon_sym_DOT,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    STATE(37), 2,
      sym_comment,
      aux_sym_multi_data_declaration_repeat1,
  [986] = 6,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(145), 1,
      aux_sym__immediate_identifier_token1,
    STATE(38), 1,
      sym_comment,
    STATE(51), 1,
      sym__immediate_identifier,
  [1005] = 6,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(124), 1,
      sym_identifier,
    STATE(39), 1,
      sym_comment,
    STATE(42), 1,
      sym_data_declaration,
  [1024] = 6,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(124), 1,
      sym_identifier,
    STATE(36), 1,
      sym_data_declaration,
    STATE(40), 1,
      sym_comment,
  [1043] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(41), 1,
      sym_comment,
    ACTIONS(147), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [1060] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(42), 1,
      sym_comment,
    ACTIONS(140), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [1077] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_comment,
  [1093] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(151), 1,
      anon_sym_DOT,
    STATE(44), 1,
      sym_comment,
  [1109] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(153), 1,
      aux_sym__data_value_token3,
    STATE(45), 1,
      sym_comment,
  [1125] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(155), 1,
      anon_sym_DOT,
    STATE(46), 1,
      sym_comment,
  [1141] = 5,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(157), 1,
      aux_sym_literal_string_token1,
    ACTIONS(159), 1,
      sym__inline_comment,
    STATE(47), 1,
      sym_comment,
  [1157] = 5,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(159), 1,
      sym__inline_comment,
    ACTIONS(161), 1,
      aux_sym_literal_string_token2,
    STATE(48), 1,
      sym_comment,
  [1173] = 5,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(159), 1,
      sym__inline_comment,
    ACTIONS(163), 1,
      aux_sym_comment_token1,
    STATE(49), 1,
      sym_comment,
  [1189] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_comment,
  [1205] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      sym_comment,
  [1221] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      sym_comment,
  [1237] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(171), 1,
      sym_number,
    STATE(53), 1,
      sym_comment,
  [1253] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(54), 1,
      sym_comment,
  [1269] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(175), 1,
      aux_sym__scalar_declaration_body_token1,
    STATE(55), 1,
      sym_comment,
  [1285] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(126), 1,
      anon_sym_LPAREN,
    STATE(56), 1,
      sym_comment,
  [1301] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    STATE(57), 1,
      sym_comment,
  [1317] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(177), 1,
      anon_sym_BQUOTE,
    STATE(58), 1,
      sym_comment,
  [1333] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(179), 1,
      anon_sym_DOT,
    STATE(59), 1,
      sym_comment,
  [1349] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(181), 1,
      anon_sym_DOT,
    STATE(60), 1,
      sym_comment,
  [1365] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(183), 1,
      sym_type,
    STATE(61), 1,
      sym_comment,
  [1381] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(62), 1,
      sym_comment,
  [1397] = 1,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
  [1401] = 1,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 59,
  [SMALL_STATE(4)] = 112,
  [SMALL_STATE(5)] = 165,
  [SMALL_STATE(6)] = 216,
  [SMALL_STATE(7)] = 265,
  [SMALL_STATE(8)] = 305,
  [SMALL_STATE(9)] = 343,
  [SMALL_STATE(10)] = 366,
  [SMALL_STATE(11)] = 389,
  [SMALL_STATE(12)] = 412,
  [SMALL_STATE(13)] = 435,
  [SMALL_STATE(14)] = 458,
  [SMALL_STATE(15)] = 481,
  [SMALL_STATE(16)] = 504,
  [SMALL_STATE(17)] = 527,
  [SMALL_STATE(18)] = 550,
  [SMALL_STATE(19)] = 573,
  [SMALL_STATE(20)] = 596,
  [SMALL_STATE(21)] = 619,
  [SMALL_STATE(22)] = 642,
  [SMALL_STATE(23)] = 670,
  [SMALL_STATE(24)] = 698,
  [SMALL_STATE(25)] = 720,
  [SMALL_STATE(26)] = 739,
  [SMALL_STATE(27)] = 764,
  [SMALL_STATE(28)] = 783,
  [SMALL_STATE(29)] = 802,
  [SMALL_STATE(30)] = 821,
  [SMALL_STATE(31)] = 840,
  [SMALL_STATE(32)] = 859,
  [SMALL_STATE(33)] = 884,
  [SMALL_STATE(34)] = 903,
  [SMALL_STATE(35)] = 922,
  [SMALL_STATE(36)] = 944,
  [SMALL_STATE(37)] = 966,
  [SMALL_STATE(38)] = 986,
  [SMALL_STATE(39)] = 1005,
  [SMALL_STATE(40)] = 1024,
  [SMALL_STATE(41)] = 1043,
  [SMALL_STATE(42)] = 1060,
  [SMALL_STATE(43)] = 1077,
  [SMALL_STATE(44)] = 1093,
  [SMALL_STATE(45)] = 1109,
  [SMALL_STATE(46)] = 1125,
  [SMALL_STATE(47)] = 1141,
  [SMALL_STATE(48)] = 1157,
  [SMALL_STATE(49)] = 1173,
  [SMALL_STATE(50)] = 1189,
  [SMALL_STATE(51)] = 1205,
  [SMALL_STATE(52)] = 1221,
  [SMALL_STATE(53)] = 1237,
  [SMALL_STATE(54)] = 1253,
  [SMALL_STATE(55)] = 1269,
  [SMALL_STATE(56)] = 1285,
  [SMALL_STATE(57)] = 1301,
  [SMALL_STATE(58)] = 1317,
  [SMALL_STATE(59)] = 1333,
  [SMALL_STATE(60)] = 1349,
  [SMALL_STATE(61)] = 1365,
  [SMALL_STATE(62)] = 1381,
  [SMALL_STATE(63)] = 1397,
  [SMALL_STATE(64)] = 1401,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_declaration, 1, 0, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scalar_declaration_body, 1, 0, 9),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scalar_declaration_body, 4, 0, 12),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(9),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(61),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(62),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(22),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(26),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(53),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 2),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 4),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 6),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 5),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 7),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 8),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_value, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_string, 3, 0, 13),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_decimals, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__like_reference, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_value, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_reference, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_length, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_declaration, 4, 0, 10),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_data_declaration, 4, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_report_statement, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_statement, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_data_declaration, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_data_declaration, 5, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_declaration, 7, 0, 14),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multi_data_declaration_repeat1, 2, 0, 0),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multi_data_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_declaration, 2, 0, 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__immediate_identifier, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [169] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__begin_line_comment = 0,
  ts_external_token__whitespace = 1,
  ts_external_token__error_sentinel = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__begin_line_comment] = sym__begin_line_comment,
  [ts_external_token__whitespace] = sym__whitespace,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__begin_line_comment] = true,
    [ts_external_token__whitespace] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__begin_line_comment] = true,
    [ts_external_token__whitespace] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_abap_external_scanner_create(void);
void tree_sitter_abap_external_scanner_destroy(void *);
bool tree_sitter_abap_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_abap_external_scanner_serialize(void *, char *);
void tree_sitter_abap_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_abap(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_abap_external_scanner_create,
      tree_sitter_abap_external_scanner_destroy,
      tree_sitter_abap_external_scanner_scan,
      tree_sitter_abap_external_scanner_serialize,
      tree_sitter_abap_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "abap",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
