/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 89
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 21
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_inline_declaration_token1 = 2,
  aux_sym_inline_declaration_token2 = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_EQ = 6,
  anon_sym_DOT = 7,
  aux_sym__scalar_declaration_body_token1 = 8,
  aux_sym__scalar_declaration_body_token2 = 9,
  aux_sym_struct_spec_token1 = 10,
  aux_sym_struct_spec_token2 = 11,
  anon_sym_COMMA = 12,
  aux_sym_struct_spec_token3 = 13,
  anon_sym_COLON = 14,
  aux_sym_report_statement_token1 = 15,
  aux_sym__type_reference_token1 = 16,
  aux_sym__like_reference_token1 = 17,
  aux_sym__data_value_token1 = 18,
  aux_sym__data_value_token2 = 19,
  aux_sym__data_value_token3 = 20,
  aux_sym__data_length_token1 = 21,
  aux_sym__data_decimals_token1 = 22,
  sym_type = 23,
  sym_number = 24,
  aux_sym__immediate_identifier_token1 = 25,
  anon_sym_SQUOTE = 26,
  aux_sym_literal_string_token1 = 27,
  anon_sym_BQUOTE = 28,
  aux_sym_literal_string_token2 = 29,
  aux_sym_comment_token1 = 30,
  sym__inline_comment = 31,
  sym__begin_line_comment = 32,
  sym__whitespace = 33,
  sym__error_sentinel = 34,
  sym_source = 35,
  sym__statement = 36,
  sym__simple_statement = 37,
  sym_inline_declaration = 38,
  sym__expression = 39,
  sym__scalar_declaration_body = 40,
  sym__struct_field = 41,
  sym_struct_spec = 42,
  sym_data_spec = 43,
  sym_data_declaration = 44,
  sym_report_statement = 45,
  sym__type_reference = 46,
  sym__like_reference = 47,
  sym__data_value = 48,
  sym__data_length = 49,
  sym__data_decimals = 50,
  sym__immediate_identifier = 51,
  sym_literal_string = 52,
  sym_comment = 53,
  aux_sym_source_repeat1 = 54,
  aux_sym__scalar_declaration_body_repeat1 = 55,
  aux_sym_struct_spec_repeat1 = 56,
  aux_sym_data_declaration_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_inline_declaration_token1] = "data",
  [aux_sym_inline_declaration_token2] = "final",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [aux_sym__scalar_declaration_body_token1] = "number",
  [aux_sym__scalar_declaration_body_token2] = "read-only",
  [aux_sym_struct_spec_token1] = "begin",
  [aux_sym_struct_spec_token2] = "of",
  [anon_sym_COMMA] = ",",
  [aux_sym_struct_spec_token3] = "end",
  [anon_sym_COLON] = ":",
  [aux_sym_report_statement_token1] = "report",
  [aux_sym__type_reference_token1] = "type",
  [aux_sym__like_reference_token1] = "like",
  [aux_sym__data_value_token1] = "value",
  [aux_sym__data_value_token2] = "is",
  [aux_sym__data_value_token3] = "initial",
  [aux_sym__data_length_token1] = "length",
  [aux_sym__data_decimals_token1] = "decimals",
  [sym_type] = "type",
  [sym_number] = "number",
  [aux_sym__immediate_identifier_token1] = "identifier",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_literal_string_token1] = "literal_string_token1",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_literal_string_token2] = "literal_string_token2",
  [aux_sym_comment_token1] = "comment_token1",
  [sym__inline_comment] = "_inline_comment",
  [sym__begin_line_comment] = "_begin_line_comment",
  [sym__whitespace] = "_whitespace",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_source] = "source",
  [sym__statement] = "_statement",
  [sym__simple_statement] = "_simple_statement",
  [sym_inline_declaration] = "inline_declaration",
  [sym__expression] = "_expression",
  [sym__scalar_declaration_body] = "_scalar_declaration_body",
  [sym__struct_field] = "_struct_field",
  [sym_struct_spec] = "struct_spec",
  [sym_data_spec] = "data_spec",
  [sym_data_declaration] = "data_declaration",
  [sym_report_statement] = "report_statement",
  [sym__type_reference] = "_type_reference",
  [sym__like_reference] = "_like_reference",
  [sym__data_value] = "_data_value",
  [sym__data_length] = "_data_length",
  [sym__data_decimals] = "_data_decimals",
  [sym__immediate_identifier] = "_immediate_identifier",
  [sym_literal_string] = "literal_string",
  [sym_comment] = "comment",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym__scalar_declaration_body_repeat1] = "_scalar_declaration_body_repeat1",
  [aux_sym_struct_spec_repeat1] = "struct_spec_repeat1",
  [aux_sym_data_declaration_repeat1] = "data_declaration_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_inline_declaration_token1] = aux_sym_inline_declaration_token1,
  [aux_sym_inline_declaration_token2] = aux_sym_inline_declaration_token2,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym__scalar_declaration_body_token1] = sym_number,
  [aux_sym__scalar_declaration_body_token2] = aux_sym__scalar_declaration_body_token2,
  [aux_sym_struct_spec_token1] = aux_sym_struct_spec_token1,
  [aux_sym_struct_spec_token2] = aux_sym_struct_spec_token2,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_struct_spec_token3] = aux_sym_struct_spec_token3,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_report_statement_token1] = aux_sym_report_statement_token1,
  [aux_sym__type_reference_token1] = aux_sym__type_reference_token1,
  [aux_sym__like_reference_token1] = aux_sym__like_reference_token1,
  [aux_sym__data_value_token1] = aux_sym__data_value_token1,
  [aux_sym__data_value_token2] = aux_sym__data_value_token2,
  [aux_sym__data_value_token3] = aux_sym__data_value_token3,
  [aux_sym__data_length_token1] = aux_sym__data_length_token1,
  [aux_sym__data_decimals_token1] = aux_sym__data_decimals_token1,
  [sym_type] = sym_type,
  [sym_number] = sym_number,
  [aux_sym__immediate_identifier_token1] = sym_identifier,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_literal_string_token1] = aux_sym_literal_string_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_literal_string_token2] = aux_sym_literal_string_token2,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym__inline_comment] = sym__inline_comment,
  [sym__begin_line_comment] = sym__begin_line_comment,
  [sym__whitespace] = sym__whitespace,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_source] = sym_source,
  [sym__statement] = sym__statement,
  [sym__simple_statement] = sym__simple_statement,
  [sym_inline_declaration] = sym_inline_declaration,
  [sym__expression] = sym__expression,
  [sym__scalar_declaration_body] = sym__scalar_declaration_body,
  [sym__struct_field] = sym__struct_field,
  [sym_struct_spec] = sym_struct_spec,
  [sym_data_spec] = sym_data_spec,
  [sym_data_declaration] = sym_data_declaration,
  [sym_report_statement] = sym_report_statement,
  [sym__type_reference] = sym__type_reference,
  [sym__like_reference] = sym__like_reference,
  [sym__data_value] = sym__data_value,
  [sym__data_length] = sym__data_length,
  [sym__data_decimals] = sym__data_decimals,
  [sym__immediate_identifier] = sym__immediate_identifier,
  [sym_literal_string] = sym_literal_string,
  [sym_comment] = sym_comment,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym__scalar_declaration_body_repeat1] = aux_sym__scalar_declaration_body_repeat1,
  [aux_sym_struct_spec_repeat1] = aux_sym_struct_spec_repeat1,
  [aux_sym_data_declaration_repeat1] = aux_sym_data_declaration_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_inline_declaration_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_inline_declaration_token2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__scalar_declaration_body_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__scalar_declaration_body_token2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_struct_spec_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_struct_spec_token2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_struct_spec_token3] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_report_statement_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__type_reference_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__like_reference_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_value_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_value_token2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_value_token3] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_length_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__data_decimals_token1] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__immediate_identifier_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_literal_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_literal_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__inline_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__begin_line_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_inline_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__scalar_declaration_body] = {
    .visible = false,
    .named = true,
  },
  [sym__struct_field] = {
    .visible = false,
    .named = true,
  },
  [sym_struct_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_data_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_data_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_report_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__type_reference] = {
    .visible = false,
    .named = true,
  },
  [sym__like_reference] = {
    .visible = false,
    .named = true,
  },
  [sym__data_value] = {
    .visible = false,
    .named = true,
  },
  [sym__data_length] = {
    .visible = false,
    .named = true,
  },
  [sym__data_decimals] = {
    .visible = false,
    .named = true,
  },
  [sym__immediate_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_literal_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__scalar_declaration_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_spec_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bufsize = 1,
  field_content = 2,
  field_decimals = 3,
  field_field = 4,
  field_length = 5,
  field_like = 6,
  field_name = 7,
  field_nameClose = 8,
  field_nameOpen = 9,
  field_readonly = 10,
  field_type = 11,
  field_value = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bufsize] = "bufsize",
  [field_content] = "content",
  [field_decimals] = "decimals",
  [field_field] = "field",
  [field_length] = "length",
  [field_like] = "like",
  [field_name] = "name",
  [field_nameClose] = "nameClose",
  [field_nameOpen] = "nameOpen",
  [field_readonly] = "readonly",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 8},
  [4] = {.index = 10, .length = 1},
  [5] = {.index = 11, .length = 1},
  [6] = {.index = 12, .length = 1},
  [7] = {.index = 13, .length = 1},
  [8] = {.index = 14, .length = 1},
  [9] = {.index = 15, .length = 6},
  [10] = {.index = 21, .length = 1},
  [11] = {.index = 22, .length = 12},
  [12] = {.index = 34, .length = 9},
  [13] = {.index = 43, .length = 1},
  [14] = {.index = 44, .length = 2},
  [15] = {.index = 46, .length = 1},
  [16] = {.index = 47, .length = 2},
  [17] = {.index = 49, .length = 2},
  [18] = {.index = 51, .length = 2},
  [19] = {.index = 53, .length = 3},
  [20] = {.index = 56, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_readonly, 0},
  [2] =
    {field_bufsize, 1, .inherited = true},
    {field_decimals, 1, .inherited = true},
    {field_length, 1, .inherited = true},
    {field_like, 1, .inherited = true},
    {field_name, 0},
    {field_readonly, 1, .inherited = true},
    {field_type, 1, .inherited = true},
    {field_value, 1, .inherited = true},
  [10] =
    {field_type, 0},
  [11] =
    {field_like, 0},
  [12] =
    {field_value, 0},
  [13] =
    {field_length, 0},
  [14] =
    {field_decimals, 0},
  [15] =
    {field_decimals, 0, .inherited = true},
    {field_length, 0, .inherited = true},
    {field_like, 0, .inherited = true},
    {field_readonly, 0, .inherited = true},
    {field_type, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [21] =
    {field_name, 2},
  [22] =
    {field_decimals, 0, .inherited = true},
    {field_decimals, 1, .inherited = true},
    {field_length, 0, .inherited = true},
    {field_length, 1, .inherited = true},
    {field_like, 0, .inherited = true},
    {field_like, 1, .inherited = true},
    {field_readonly, 0, .inherited = true},
    {field_readonly, 1, .inherited = true},
    {field_type, 0, .inherited = true},
    {field_type, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [34] =
    {field_bufsize, 0},
    {field_bufsize, 1},
    {field_bufsize, 2},
    {field_decimals, 3, .inherited = true},
    {field_length, 3, .inherited = true},
    {field_like, 3, .inherited = true},
    {field_readonly, 3, .inherited = true},
    {field_type, 3, .inherited = true},
    {field_value, 3, .inherited = true},
  [43] =
    {field_content, 1},
  [44] =
    {field_name, 2},
    {field_value, 5},
  [46] =
    {field_field, 0},
  [47] =
    {field_field, 0, .inherited = true},
    {field_field, 1, .inherited = true},
  [49] =
    {field_nameClose, 6},
    {field_nameOpen, 2},
  [51] =
    {field_nameClose, 7},
    {field_nameOpen, 2},
  [53] =
    {field_field, 4, .inherited = true},
    {field_nameClose, 7},
    {field_nameOpen, 2},
  [56] =
    {field_field, 5, .inherited = true},
    {field_nameClose, 8},
    {field_nameOpen, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym__simple_statement,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym__simple_statement] = {.index = 0, .length = 3},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_data_declaration,
    sym_inline_declaration,
    sym_report_statement,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 28,
        '\'', 18,
        '(', 7,
        ')', 8,
        ',', 12,
        '-', 3,
        '.', 10,
        ':', 13,
        '=', 9,
        '`', 22,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '-') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 28,
        '\'', 18,
        '(', 7,
        ',', 12,
        '-', 4,
        '.', 10,
        ':', 13,
        '=', 9,
        '`', 22,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__scalar_declaration_body_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__immediate_identifier_token1);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_literal_string_token1);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_literal_string_token1);
      if (lookahead == '\'') ADVANCE(28);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(21);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_literal_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_literal_string_token2);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_literal_string_token2);
      if (lookahead == '`') ADVANCE(28);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(25);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_literal_string_token2);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '"') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__inline_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(28);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'B', 1,
        'b', 1,
        'D', 2,
        'd', 2,
        'E', 3,
        'e', 3,
        'F', 4,
        'f', 4,
        'I', 5,
        'i', 5,
        'L', 6,
        'l', 6,
        'O', 7,
        'o', 7,
        'R', 8,
        'r', 8,
        'T', 9,
        't', 9,
        'V', 10,
        'v', 10,
      );
      END_STATE();
    case 1:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(12);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(16);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(18);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__data_value_token2);
      END_STATE();
    case 18:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'K' ||
          lookahead == 'k') ADVANCE(31);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_struct_spec_token2);
      END_STATE();
    case 21:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(32);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 24:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 25:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_struct_spec_token3);
      END_STATE();
    case 28:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 34:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(46);
      END_STATE();
    case 36:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_inline_declaration_token1);
      END_STATE();
    case 38:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(48);
      END_STATE();
    case 39:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 40:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 41:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(51);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__like_reference_token1);
      END_STATE();
    case 43:
      if (lookahead == '-') ADVANCE(52);
      END_STATE();
    case 44:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__type_reference_token1);
      END_STATE();
    case 46:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_struct_spec_token1);
      END_STATE();
    case 48:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(55);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_inline_declaration_token2);
      END_STATE();
    case 50:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 51:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(57);
      END_STATE();
    case 52:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(58);
      END_STATE();
    case 53:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(59);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym__data_value_token1);
      END_STATE();
    case 55:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 56:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym__data_length_token1);
      END_STATE();
    case 58:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_report_statement_token1);
      END_STATE();
    case 60:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym__data_value_token3);
      END_STATE();
    case 62:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym__data_decimals_token1);
      END_STATE();
    case 64:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym__scalar_declaration_body_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 5, .external_lex_state = 2},
  [2] = {.lex_state = 5, .external_lex_state = 2},
  [3] = {.lex_state = 5, .external_lex_state = 2},
  [4] = {.lex_state = 5, .external_lex_state = 2},
  [5] = {.lex_state = 5, .external_lex_state = 2},
  [6] = {.lex_state = 5, .external_lex_state = 2},
  [7] = {.lex_state = 5, .external_lex_state = 2},
  [8] = {.lex_state = 5, .external_lex_state = 2},
  [9] = {.lex_state = 5, .external_lex_state = 2},
  [10] = {.lex_state = 5, .external_lex_state = 2},
  [11] = {.lex_state = 5, .external_lex_state = 2},
  [12] = {.lex_state = 5, .external_lex_state = 2},
  [13] = {.lex_state = 5, .external_lex_state = 2},
  [14] = {.lex_state = 5, .external_lex_state = 2},
  [15] = {.lex_state = 5, .external_lex_state = 2},
  [16] = {.lex_state = 5, .external_lex_state = 2},
  [17] = {.lex_state = 5, .external_lex_state = 2},
  [18] = {.lex_state = 5, .external_lex_state = 2},
  [19] = {.lex_state = 5, .external_lex_state = 2},
  [20] = {.lex_state = 5, .external_lex_state = 2},
  [21] = {.lex_state = 5, .external_lex_state = 2},
  [22] = {.lex_state = 5, .external_lex_state = 2},
  [23] = {.lex_state = 5, .external_lex_state = 2},
  [24] = {.lex_state = 5, .external_lex_state = 2},
  [25] = {.lex_state = 5, .external_lex_state = 2},
  [26] = {.lex_state = 5, .external_lex_state = 2},
  [27] = {.lex_state = 5, .external_lex_state = 2},
  [28] = {.lex_state = 5, .external_lex_state = 2},
  [29] = {.lex_state = 5, .external_lex_state = 2},
  [30] = {.lex_state = 5, .external_lex_state = 2},
  [31] = {.lex_state = 5, .external_lex_state = 2},
  [32] = {.lex_state = 5, .external_lex_state = 2},
  [33] = {.lex_state = 5, .external_lex_state = 2},
  [34] = {.lex_state = 5, .external_lex_state = 2},
  [35] = {.lex_state = 5, .external_lex_state = 2},
  [36] = {.lex_state = 5, .external_lex_state = 2},
  [37] = {.lex_state = 5, .external_lex_state = 2},
  [38] = {.lex_state = 5, .external_lex_state = 2},
  [39] = {.lex_state = 5, .external_lex_state = 2},
  [40] = {.lex_state = 5, .external_lex_state = 2},
  [41] = {.lex_state = 5, .external_lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 5, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 5, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 1, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 0, .external_lex_state = 2},
  [53] = {.lex_state = 0, .external_lex_state = 2},
  [54] = {.lex_state = 5, .external_lex_state = 2},
  [55] = {.lex_state = 19, .external_lex_state = 2},
  [56] = {.lex_state = 23, .external_lex_state = 2},
  [57] = {.lex_state = 26, .external_lex_state = 2},
  [58] = {.lex_state = 5, .external_lex_state = 2},
  [59] = {.lex_state = 1, .external_lex_state = 2},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 2},
  [62] = {.lex_state = 0, .external_lex_state = 2},
  [63] = {.lex_state = 0, .external_lex_state = 2},
  [64] = {.lex_state = 0, .external_lex_state = 2},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 2, .external_lex_state = 2},
  [67] = {.lex_state = 5, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 2},
  [69] = {.lex_state = 5, .external_lex_state = 2},
  [70] = {.lex_state = 0, .external_lex_state = 2},
  [71] = {.lex_state = 0, .external_lex_state = 2},
  [72] = {.lex_state = 5, .external_lex_state = 2},
  [73] = {.lex_state = 5, .external_lex_state = 2},
  [74] = {.lex_state = 5, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 5, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 5, .external_lex_state = 2},
  [79] = {.lex_state = 5, .external_lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 2},
  [81] = {.lex_state = 5, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 2},
  [83] = {.lex_state = 5, .external_lex_state = 2},
  [84] = {.lex_state = 5, .external_lex_state = 2},
  [85] = {.lex_state = 0, .external_lex_state = 2},
  [86] = {.lex_state = 5, .external_lex_state = 2},
  [87] = {(TSStateId)(-1),},
  [88] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_inline_declaration_token1] = ACTIONS(1),
    [aux_sym_inline_declaration_token2] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym__scalar_declaration_body_token1] = ACTIONS(1),
    [aux_sym__scalar_declaration_body_token2] = ACTIONS(1),
    [aux_sym_struct_spec_token1] = ACTIONS(1),
    [aux_sym_struct_spec_token2] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_struct_spec_token3] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_report_statement_token1] = ACTIONS(1),
    [aux_sym__type_reference_token1] = ACTIONS(1),
    [aux_sym__like_reference_token1] = ACTIONS(1),
    [aux_sym__data_value_token1] = ACTIONS(1),
    [aux_sym__data_value_token2] = ACTIONS(1),
    [aux_sym__data_value_token3] = ACTIONS(1),
    [aux_sym__data_length_token1] = ACTIONS(1),
    [aux_sym__data_decimals_token1] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym__immediate_identifier_token1] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym__inline_comment] = ACTIONS(3),
    [sym__begin_line_comment] = ACTIONS(5),
    [sym__whitespace] = ACTIONS(7),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(68),
    [sym__statement] = STATE(39),
    [sym__simple_statement] = STATE(31),
    [sym_inline_declaration] = STATE(32),
    [sym_data_declaration] = STATE(32),
    [sym_report_statement] = STATE(32),
    [sym_comment] = STATE(1),
    [aux_sym_source_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(9),
    [aux_sym_inline_declaration_token1] = ACTIONS(11),
    [aux_sym_inline_declaration_token2] = ACTIONS(13),
    [aux_sym_report_statement_token1] = ACTIONS(15),
    [sym__inline_comment] = ACTIONS(3),
    [sym__begin_line_comment] = ACTIONS(5),
    [sym__whitespace] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      aux_sym__scalar_declaration_body_token2,
    ACTIONS(23), 1,
      aux_sym__type_reference_token1,
    ACTIONS(25), 1,
      aux_sym__like_reference_token1,
    ACTIONS(27), 1,
      aux_sym__data_value_token1,
    ACTIONS(29), 1,
      aux_sym__data_length_token1,
    ACTIONS(31), 1,
      aux_sym__data_decimals_token1,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      aux_sym__scalar_declaration_body_repeat1,
    STATE(9), 1,
      sym__like_reference,
    STATE(11), 1,
      sym__type_reference,
    STATE(12), 1,
      sym__data_value,
    STATE(13), 1,
      sym__data_decimals,
    STATE(14), 1,
      sym__data_length,
    STATE(50), 1,
      sym__scalar_declaration_body,
    ACTIONS(19), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [59] = 17,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(21), 1,
      aux_sym__scalar_declaration_body_token2,
    ACTIONS(23), 1,
      aux_sym__type_reference_token1,
    ACTIONS(25), 1,
      aux_sym__like_reference_token1,
    ACTIONS(27), 1,
      aux_sym__data_value_token1,
    ACTIONS(29), 1,
      aux_sym__data_length_token1,
    ACTIONS(31), 1,
      aux_sym__data_decimals_token1,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym__scalar_declaration_body_repeat1,
    STATE(9), 1,
      sym__like_reference,
    STATE(11), 1,
      sym__type_reference,
    STATE(12), 1,
      sym__data_value,
    STATE(13), 1,
      sym__data_decimals,
    STATE(14), 1,
      sym__data_length,
    ACTIONS(33), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [112] = 16,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(37), 1,
      aux_sym__scalar_declaration_body_token2,
    ACTIONS(40), 1,
      aux_sym__type_reference_token1,
    ACTIONS(43), 1,
      aux_sym__like_reference_token1,
    ACTIONS(46), 1,
      aux_sym__data_value_token1,
    ACTIONS(49), 1,
      aux_sym__data_length_token1,
    ACTIONS(52), 1,
      aux_sym__data_decimals_token1,
    STATE(9), 1,
      sym__like_reference,
    STATE(11), 1,
      sym__type_reference,
    STATE(12), 1,
      sym__data_value,
    STATE(13), 1,
      sym__data_decimals,
    STATE(14), 1,
      sym__data_length,
    ACTIONS(35), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
    STATE(4), 2,
      sym_comment,
      aux_sym__scalar_declaration_body_repeat1,
  [163] = 17,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(21), 1,
      aux_sym__scalar_declaration_body_token2,
    ACTIONS(23), 1,
      aux_sym__type_reference_token1,
    ACTIONS(25), 1,
      aux_sym__like_reference_token1,
    ACTIONS(27), 1,
      aux_sym__data_value_token1,
    ACTIONS(29), 1,
      aux_sym__data_length_token1,
    ACTIONS(31), 1,
      aux_sym__data_decimals_token1,
    STATE(4), 1,
      aux_sym__scalar_declaration_body_repeat1,
    STATE(5), 1,
      sym_comment,
    STATE(9), 1,
      sym__like_reference,
    STATE(11), 1,
      sym__type_reference,
    STATE(12), 1,
      sym__data_value,
    STATE(13), 1,
      sym__data_decimals,
    STATE(14), 1,
      sym__data_length,
    ACTIONS(55), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [216] = 16,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(21), 1,
      aux_sym__scalar_declaration_body_token2,
    ACTIONS(23), 1,
      aux_sym__type_reference_token1,
    ACTIONS(25), 1,
      aux_sym__like_reference_token1,
    ACTIONS(27), 1,
      aux_sym__data_value_token1,
    ACTIONS(29), 1,
      aux_sym__data_length_token1,
    ACTIONS(31), 1,
      aux_sym__data_decimals_token1,
    STATE(5), 1,
      aux_sym__scalar_declaration_body_repeat1,
    STATE(6), 1,
      sym_comment,
    STATE(9), 1,
      sym__like_reference,
    STATE(11), 1,
      sym__type_reference,
    STATE(12), 1,
      sym__data_value,
    STATE(13), 1,
      sym__data_decimals,
    STATE(14), 1,
      sym__data_length,
  [265] = 11,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      aux_sym_inline_declaration_token1,
    ACTIONS(62), 1,
      aux_sym_inline_declaration_token2,
    ACTIONS(65), 1,
      aux_sym_report_statement_token1,
    STATE(31), 1,
      sym__simple_statement,
    STATE(39), 1,
      sym__statement,
    STATE(7), 2,
      sym_comment,
      aux_sym_source_repeat1,
    STATE(32), 3,
      sym_inline_declaration,
      sym_data_declaration,
      sym_report_statement,
  [302] = 12,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(11), 1,
      aux_sym_inline_declaration_token1,
    ACTIONS(13), 1,
      aux_sym_inline_declaration_token2,
    ACTIONS(15), 1,
      aux_sym_report_statement_token1,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_source_repeat1,
    STATE(8), 1,
      sym_comment,
    STATE(31), 1,
      sym__simple_statement,
    STATE(39), 1,
      sym__statement,
    STATE(32), 3,
      sym_inline_declaration,
      sym_data_declaration,
      sym_report_statement,
  [341] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(9), 1,
      sym_comment,
    ACTIONS(70), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [364] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(10), 1,
      sym_comment,
    ACTIONS(72), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [387] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(11), 1,
      sym_comment,
    ACTIONS(74), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [410] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(12), 1,
      sym_comment,
    ACTIONS(76), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [433] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(13), 1,
      sym_comment,
    ACTIONS(78), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [456] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(14), 1,
      sym_comment,
    ACTIONS(80), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [479] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(15), 1,
      sym_comment,
    ACTIONS(82), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [502] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(16), 1,
      sym_comment,
    ACTIONS(84), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [525] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(17), 1,
      sym_comment,
    ACTIONS(86), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [548] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(18), 1,
      sym_comment,
    ACTIONS(88), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [571] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(19), 1,
      sym_comment,
    ACTIONS(90), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [594] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(20), 1,
      sym_comment,
    ACTIONS(92), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [617] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(21), 1,
      sym_comment,
    ACTIONS(94), 8,
      anon_sym_DOT,
      aux_sym__scalar_declaration_body_token2,
      anon_sym_COMMA,
      aux_sym__type_reference_token1,
      aux_sym__like_reference_token1,
      aux_sym__data_value_token1,
      aux_sym__data_length_token1,
      aux_sym__data_decimals_token1,
  [640] = 10,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(98), 1,
      aux_sym_struct_spec_token1,
    ACTIONS(100), 1,
      aux_sym_struct_spec_token3,
    STATE(22), 1,
      sym_comment,
    STATE(25), 1,
      aux_sym_struct_spec_repeat1,
    STATE(70), 1,
      sym__struct_field,
    STATE(71), 2,
      sym_struct_spec,
      sym_data_spec,
  [672] = 10,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(98), 1,
      aux_sym_struct_spec_token1,
    ACTIONS(102), 1,
      aux_sym_struct_spec_token3,
    STATE(23), 1,
      sym_comment,
    STATE(24), 1,
      aux_sym_struct_spec_repeat1,
    STATE(70), 1,
      sym__struct_field,
    STATE(71), 2,
      sym_struct_spec,
      sym_data_spec,
  [704] = 10,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(98), 1,
      aux_sym_struct_spec_token1,
    ACTIONS(104), 1,
      aux_sym_struct_spec_token3,
    STATE(24), 1,
      sym_comment,
    STATE(26), 1,
      aux_sym_struct_spec_repeat1,
    STATE(70), 1,
      sym__struct_field,
    STATE(71), 2,
      sym_struct_spec,
      sym_data_spec,
  [736] = 10,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(98), 1,
      aux_sym_struct_spec_token1,
    ACTIONS(106), 1,
      aux_sym_struct_spec_token3,
    STATE(25), 1,
      sym_comment,
    STATE(26), 1,
      aux_sym_struct_spec_repeat1,
    STATE(70), 1,
      sym__struct_field,
    STATE(71), 2,
      sym_struct_spec,
      sym_data_spec,
  [768] = 9,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(108), 1,
      sym_identifier,
    ACTIONS(111), 1,
      aux_sym_struct_spec_token1,
    ACTIONS(114), 1,
      aux_sym_struct_spec_token3,
    STATE(70), 1,
      sym__struct_field,
    STATE(26), 2,
      sym_comment,
      aux_sym_struct_spec_repeat1,
    STATE(71), 2,
      sym_struct_spec,
      sym_data_spec,
  [798] = 9,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(116), 1,
      aux_sym__data_value_token2,
    ACTIONS(118), 1,
      sym_number,
    ACTIONS(120), 1,
      anon_sym_SQUOTE,
    ACTIONS(122), 1,
      anon_sym_BQUOTE,
    STATE(19), 1,
      sym_literal_string,
    STATE(27), 1,
      sym_comment,
  [826] = 6,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(126), 1,
      anon_sym_EQ,
    STATE(28), 1,
      sym_comment,
    ACTIONS(124), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [848] = 9,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(120), 1,
      anon_sym_SQUOTE,
    ACTIONS(122), 1,
      anon_sym_BQUOTE,
    ACTIONS(128), 1,
      sym_number,
    STATE(29), 1,
      sym_comment,
    STATE(62), 1,
      sym_literal_string,
    STATE(63), 1,
      sym__expression,
  [876] = 8,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_COLON,
    STATE(30), 1,
      sym_comment,
    STATE(75), 1,
      sym_data_spec,
  [901] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(31), 1,
      sym_comment,
    ACTIONS(136), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [920] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(32), 1,
      sym_comment,
    ACTIONS(138), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [939] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(33), 1,
      sym_comment,
    ACTIONS(140), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [958] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(34), 1,
      sym_comment,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [977] = 7,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(98), 1,
      aux_sym_struct_spec_token1,
    STATE(35), 1,
      sym_comment,
    STATE(42), 2,
      sym_struct_spec,
      sym_data_spec,
  [1000] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(36), 1,
      sym_comment,
    ACTIONS(144), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [1019] = 7,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(98), 1,
      aux_sym_struct_spec_token1,
    STATE(37), 1,
      sym_comment,
    STATE(48), 2,
      sym_struct_spec,
      sym_data_spec,
  [1042] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(38), 1,
      sym_comment,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [1061] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(39), 1,
      sym_comment,
    ACTIONS(148), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [1080] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(40), 1,
      sym_comment,
    ACTIONS(150), 4,
      ts_builtin_sym_end,
      aux_sym_inline_declaration_token1,
      aux_sym_inline_declaration_token2,
      aux_sym_report_statement_token1,
  [1099] = 8,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(120), 1,
      anon_sym_SQUOTE,
    ACTIONS(122), 1,
      anon_sym_BQUOTE,
    ACTIONS(152), 1,
      sym_number,
    STATE(18), 1,
      sym_literal_string,
    STATE(41), 1,
      sym_comment,
  [1124] = 7,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(154), 1,
      anon_sym_DOT,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    STATE(42), 1,
      sym_comment,
    STATE(45), 1,
      aux_sym_data_declaration_repeat1,
  [1146] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(43), 1,
      sym_comment,
    ACTIONS(158), 3,
      aux_sym_struct_spec_token1,
      aux_sym_struct_spec_token3,
      sym_identifier,
  [1164] = 6,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(160), 1,
      anon_sym_DOT,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    STATE(44), 2,
      sym_comment,
      aux_sym_data_declaration_repeat1,
  [1184] = 7,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(165), 1,
      anon_sym_DOT,
    STATE(44), 1,
      aux_sym_data_declaration_repeat1,
    STATE(45), 1,
      sym_comment,
  [1206] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(46), 1,
      sym_comment,
    ACTIONS(167), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [1223] = 6,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(169), 1,
      aux_sym__scalar_declaration_body_token2,
    ACTIONS(171), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      sym_comment,
  [1242] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(48), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [1259] = 6,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(173), 1,
      aux_sym__immediate_identifier_token1,
    STATE(49), 1,
      sym_comment,
    STATE(82), 1,
      sym__immediate_identifier,
  [1278] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(50), 1,
      sym_comment,
    ACTIONS(175), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [1295] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(51), 1,
      sym_comment,
    ACTIONS(177), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [1312] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(52), 1,
      sym_comment,
    ACTIONS(179), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [1329] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    STATE(53), 1,
      sym_comment,
    ACTIONS(181), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [1346] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(183), 1,
      sym_identifier,
    STATE(54), 1,
      sym_comment,
  [1362] = 5,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(185), 1,
      aux_sym_literal_string_token1,
    ACTIONS(187), 1,
      sym__inline_comment,
    STATE(55), 1,
      sym_comment,
  [1378] = 5,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(187), 1,
      sym__inline_comment,
    ACTIONS(189), 1,
      aux_sym_literal_string_token2,
    STATE(56), 1,
      sym_comment,
  [1394] = 5,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(187), 1,
      sym__inline_comment,
    ACTIONS(191), 1,
      aux_sym_comment_token1,
    STATE(57), 1,
      sym_comment,
  [1410] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(58), 1,
      sym_comment,
  [1426] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(195), 1,
      aux_sym__scalar_declaration_body_token1,
    STATE(59), 1,
      sym_comment,
  [1442] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(197), 1,
      anon_sym_SQUOTE,
    STATE(60), 1,
      sym_comment,
  [1458] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(197), 1,
      anon_sym_BQUOTE,
    STATE(61), 1,
      sym_comment,
  [1474] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(199), 1,
      anon_sym_DOT,
    STATE(62), 1,
      sym_comment,
  [1490] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(201), 1,
      anon_sym_DOT,
    STATE(63), 1,
      sym_comment,
  [1506] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      sym_comment,
  [1522] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      sym_comment,
  [1538] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(207), 1,
      sym_type,
    STATE(66), 1,
      sym_comment,
  [1554] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(209), 1,
      sym_identifier,
    STATE(67), 1,
      sym_comment,
  [1570] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(211), 1,
      ts_builtin_sym_end,
    STATE(68), 1,
      sym_comment,
  [1586] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(213), 1,
      aux_sym__data_value_token3,
    STATE(69), 1,
      sym_comment,
  [1602] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      sym_comment,
  [1618] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      sym_comment,
  [1634] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(219), 1,
      aux_sym_struct_spec_token2,
    STATE(72), 1,
      sym_comment,
  [1650] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(221), 1,
      sym_number,
    STATE(73), 1,
      sym_comment,
  [1666] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(223), 1,
      sym_identifier,
    STATE(74), 1,
      sym_comment,
  [1682] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(225), 1,
      anon_sym_DOT,
    STATE(75), 1,
      sym_comment,
  [1698] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(227), 1,
      aux_sym_struct_spec_token2,
    STATE(76), 1,
      sym_comment,
  [1714] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(132), 1,
      anon_sym_LPAREN,
    STATE(77), 1,
      sym_comment,
  [1730] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(229), 1,
      sym_identifier,
    STATE(78), 1,
      sym_comment,
  [1746] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(231), 1,
      aux_sym_struct_spec_token2,
    STATE(79), 1,
      sym_comment,
  [1762] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      sym_comment,
  [1778] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(235), 1,
      sym_identifier,
    STATE(81), 1,
      sym_comment,
  [1794] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_comment,
  [1810] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(239), 1,
      sym_identifier,
    STATE(83), 1,
      sym_comment,
  [1826] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(241), 1,
      aux_sym_struct_spec_token2,
    STATE(84), 1,
      sym_comment,
  [1842] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(243), 1,
      anon_sym_DOT,
    STATE(85), 1,
      sym_comment,
  [1858] = 5,
    ACTIONS(3), 1,
      sym__inline_comment,
    ACTIONS(5), 1,
      sym__begin_line_comment,
    ACTIONS(7), 1,
      sym__whitespace,
    ACTIONS(245), 1,
      aux_sym_struct_spec_token2,
    STATE(86), 1,
      sym_comment,
  [1874] = 1,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
  [1878] = 1,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 59,
  [SMALL_STATE(4)] = 112,
  [SMALL_STATE(5)] = 163,
  [SMALL_STATE(6)] = 216,
  [SMALL_STATE(7)] = 265,
  [SMALL_STATE(8)] = 302,
  [SMALL_STATE(9)] = 341,
  [SMALL_STATE(10)] = 364,
  [SMALL_STATE(11)] = 387,
  [SMALL_STATE(12)] = 410,
  [SMALL_STATE(13)] = 433,
  [SMALL_STATE(14)] = 456,
  [SMALL_STATE(15)] = 479,
  [SMALL_STATE(16)] = 502,
  [SMALL_STATE(17)] = 525,
  [SMALL_STATE(18)] = 548,
  [SMALL_STATE(19)] = 571,
  [SMALL_STATE(20)] = 594,
  [SMALL_STATE(21)] = 617,
  [SMALL_STATE(22)] = 640,
  [SMALL_STATE(23)] = 672,
  [SMALL_STATE(24)] = 704,
  [SMALL_STATE(25)] = 736,
  [SMALL_STATE(26)] = 768,
  [SMALL_STATE(27)] = 798,
  [SMALL_STATE(28)] = 826,
  [SMALL_STATE(29)] = 848,
  [SMALL_STATE(30)] = 876,
  [SMALL_STATE(31)] = 901,
  [SMALL_STATE(32)] = 920,
  [SMALL_STATE(33)] = 939,
  [SMALL_STATE(34)] = 958,
  [SMALL_STATE(35)] = 977,
  [SMALL_STATE(36)] = 1000,
  [SMALL_STATE(37)] = 1019,
  [SMALL_STATE(38)] = 1042,
  [SMALL_STATE(39)] = 1061,
  [SMALL_STATE(40)] = 1080,
  [SMALL_STATE(41)] = 1099,
  [SMALL_STATE(42)] = 1124,
  [SMALL_STATE(43)] = 1146,
  [SMALL_STATE(44)] = 1164,
  [SMALL_STATE(45)] = 1184,
  [SMALL_STATE(46)] = 1206,
  [SMALL_STATE(47)] = 1223,
  [SMALL_STATE(48)] = 1242,
  [SMALL_STATE(49)] = 1259,
  [SMALL_STATE(50)] = 1278,
  [SMALL_STATE(51)] = 1295,
  [SMALL_STATE(52)] = 1312,
  [SMALL_STATE(53)] = 1329,
  [SMALL_STATE(54)] = 1346,
  [SMALL_STATE(55)] = 1362,
  [SMALL_STATE(56)] = 1378,
  [SMALL_STATE(57)] = 1394,
  [SMALL_STATE(58)] = 1410,
  [SMALL_STATE(59)] = 1426,
  [SMALL_STATE(60)] = 1442,
  [SMALL_STATE(61)] = 1458,
  [SMALL_STATE(62)] = 1474,
  [SMALL_STATE(63)] = 1490,
  [SMALL_STATE(64)] = 1506,
  [SMALL_STATE(65)] = 1522,
  [SMALL_STATE(66)] = 1538,
  [SMALL_STATE(67)] = 1554,
  [SMALL_STATE(68)] = 1570,
  [SMALL_STATE(69)] = 1586,
  [SMALL_STATE(70)] = 1602,
  [SMALL_STATE(71)] = 1618,
  [SMALL_STATE(72)] = 1634,
  [SMALL_STATE(73)] = 1650,
  [SMALL_STATE(74)] = 1666,
  [SMALL_STATE(75)] = 1682,
  [SMALL_STATE(76)] = 1698,
  [SMALL_STATE(77)] = 1714,
  [SMALL_STATE(78)] = 1730,
  [SMALL_STATE(79)] = 1746,
  [SMALL_STATE(80)] = 1762,
  [SMALL_STATE(81)] = 1778,
  [SMALL_STATE(82)] = 1794,
  [SMALL_STATE(83)] = 1810,
  [SMALL_STATE(84)] = 1826,
  [SMALL_STATE(85)] = 1842,
  [SMALL_STATE(86)] = 1858,
  [SMALL_STATE(87)] = 1874,
  [SMALL_STATE(88)] = 1878,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_spec, 1, 0, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scalar_declaration_body, 1, 0, 9),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(10),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(66),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(67),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(27),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(41),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 2, 0, 11), SHIFT_REPEAT(73),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scalar_declaration_body, 4, 0, 12),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 5),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 4),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 6),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 8),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scalar_declaration_body_repeat1, 1, 0, 7),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_reference, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_decimals, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__like_reference, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_length, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_value, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_value, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_string, 3, 0, 13),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_spec_repeat1, 2, 0, 16), SHIFT_REPEAT(2),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_spec_repeat1, 2, 0, 16), SHIFT_REPEAT(84),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_struct_spec_repeat1, 2, 0, 16),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_declaration, 4, 0, 10),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_statement, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_declaration, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_report_statement, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_declaration, 4, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_declaration, 5, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_declaration, 7, 0, 14),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_struct_spec_repeat1, 2, 0, 15),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_spec, 9, 0, 20),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_spec, 2, 0, 3),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_spec, 7, 0, 17),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_spec, 8, 0, 18),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_spec, 8, 0, 19),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [211] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__struct_field, 1, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__immediate_identifier, 1, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__begin_line_comment = 0,
  ts_external_token__whitespace = 1,
  ts_external_token__error_sentinel = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__begin_line_comment] = sym__begin_line_comment,
  [ts_external_token__whitespace] = sym__whitespace,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__begin_line_comment] = true,
    [ts_external_token__whitespace] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__begin_line_comment] = true,
    [ts_external_token__whitespace] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_abap_external_scanner_create(void);
void tree_sitter_abap_external_scanner_destroy(void *);
bool tree_sitter_abap_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_abap_external_scanner_serialize(void *, char *);
void tree_sitter_abap_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_abap(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_abap_external_scanner_create,
      tree_sitter_abap_external_scanner_destroy,
      tree_sitter_abap_external_scanner_scan,
      tree_sitter_abap_external_scanner_serialize,
      tree_sitter_abap_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "abap",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
